test

diff --git a/list-targets/action.yaml b/list-targets/action.yaml
--- a/list-targets/action.yaml
+++ b/list-targets/action.yaml
@@ -18,47 +18,47 @@ outputs:
 runs:
   using: composite
   steps:
-    - run: github-comment exec -- ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
-      shell: bash
-      if: |
-        ! contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name)
-      env:
-        GITHUB_TOKEN: ${{ inputs.github_token }}
+  - run: github-comment exec -- ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
+    shell: bash
+    if: |
+      ! contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name)
+    env:
+      GITHUB_TOKEN: ${{ inputs.github_token }}
 
-    - name: Check if the commit is latest
-      shell: bash
-      if: github.event_name == 'pull_request' || startsWith(github.event_name, 'pull_request_')
-      run: |
-        set -euo pipefail
+  - name: Check if the commit is latest
+    shell: bash
+    if: github.event_name == 'pull_request' || startsWith(github.event_name, 'pull_request_')
+    run: |
+      set -euo pipefail
 
-        latest_head_sha=$(jq -r ".head.sha" $CI_INFO_TEMP_DIR/pr.json)
-        if [ "$HEAD_SHA" != "$latest_head_sha" ]; then
-          echo "::error::The head sha ($HEAD_SHA) isn't latest ($latest_head_sha)."
-          exit 1
-        fi
-      env:
-        HEAD_SHA: ${{github.event.pull_request.head.sha}}
+      latest_head_sha=$(jq -r ".head.sha" $CI_INFO_TEMP_DIR/pr.json)
+      if [ "$HEAD_SHA" != "$latest_head_sha" ]; then
+        echo "::error::The head sha ($HEAD_SHA) isn't latest ($latest_head_sha)."
+        exit 1
+      fi
+    env:
+      HEAD_SHA: ${{github.event.pull_request.head.sha}}
 
-    - uses: suzuki-shunsuke/tfaction/list-working-dirs@main
-      id: list-working-directory-configs
-    - uses: suzuki-shunsuke/tfaction/get-global-config@main
-      id: global-config
-    - uses: suzuki-shunsuke/tfaction/list-module-callers@main
-      id: list-module-callers
-      if: steps.global-config.outputs.update_local_path_module_caller == 'true'
-      with:
-        config_files: ${{ steps.list-working-directory-configs.outputs.file }}
-        module_files: ${{ steps.list-working-directory-configs.outputs.module_file }}
-    - uses: suzuki-shunsuke/tfaction/list-targets-with-changed-files@main
-      id: list-targets
-      with:
-        changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
-        labels: ${{ env.CI_INFO_TEMP_DIR }}/labels.txt
-        pull_request: ${{ env.CI_INFO_TEMP_DIR }}/pr.json
-        config_files: ${{ steps.list-working-directory-configs.outputs.file }}
-        module_callers: ${{ steps.list-module-callers.outputs.file }}
-    - uses: suzuki-shunsuke/tfaction/list-changed-modules@main
-      id: list-modules
-      with:
-        changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
-        config_files: ${{ steps.list-working-directory-configs.outputs.module_file }}
+  - uses: suzuki-shunsuke/tfaction/list-working-dirs@main
+    id: list-working-directory-configs
+  - uses: suzuki-shunsuke/tfaction/get-global-config@main
+    id: global-config
+  - uses: suzuki-shunsuke/tfaction/list-module-callers@main
+    id: list-module-callers
+    if: steps.global-config.outputs.update_local_path_module_caller == 'true'
+    with:
+      config_files: ${{ steps.list-working-directory-configs.outputs.file }}
+      module_files: ${{ steps.list-working-directory-configs.outputs.module_file }}
+  - uses: cappyzawa/tfaction/list-targets-with-changed-files@b1a426e39fa1604fbba943cadc60a63c4243aded
+    id: list-targets
+    with:
+      changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
+      labels: ${{ env.CI_INFO_TEMP_DIR }}/labels.txt
+      pull_request: ${{ env.CI_INFO_TEMP_DIR }}/pr.json
+      config_files: ${{ steps.list-working-directory-configs.outputs.file }}
+      module_callers: ${{ steps.list-module-callers.outputs.file }}
+  - uses: suzuki-shunsuke/tfaction/list-changed-modules@main
+    id: list-modules
+    with:
+      changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
+      config_files: ${{ steps.list-working-directory-configs.outputs.module_file }}
